### ISSUE TITLE
Time zones returned are not pytz compatible

### ISSUE THREAD

**Issue by rabinnh** [MacHu-GWU/uszipcode-project#31]
The pytz module is the standard for time zones.  The time zones returned by uszipcode don't seem to be compatible "Eastern" is returned for most east coast cities, but 'US/Eastern' is correct:

>>> from pytz import timezone
>>> x = timezone('Eastern')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxxx/.local/lib/python3.6/site-packages/pytz/__init__.py", line 181, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: 'Eastern'
>>> x = timezone('US/Eastern')

No error with 'US/Eastern'.

**Comment by MacHu-GWU** [comment]
@rabinnh  it is because the source I crawled is natively not compatible with pytz. I think I need to iterate through all timezone info and try converting to pytz. If exception catched, then handle it differently. But it is a lot of works. Will do it in next major release.

**Comment by zevgriner** [comment]
Please make your change IANA-compatible based on Python 3.9 [zoneinfo](https://docs.python.org/3/library/zoneinfo.html) package.
Time zone labels do NOT contain daylight savings time information. For example, Arizona and Hawaii do not implement daylight savings time, and have separate IANA labels to infer that information.

**Comment by rabinnh** [comment]
Thanks MacHu.  Love the module.
