### ISSUE TITLE
Cannot operate on a closed database

### ISSUE THREAD

**Issue by mark-scherer** [MacHu-GWU/uszipcode-project#67]
Python garbage collection triggers error within `SearchEngine.__del__`:

```
Exception ignored in: <function SearchEngine.__del__ at 0x1050100d0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uszipcode/search.py", line 196, in __del__
  File "/usr/local/lib/python3.9/site-packages/uszipcode/search.py", line 202, in close
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1811, in close
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1853, in _close_impl
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 923, in close
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2416, in close
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2639, in _do_close
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2625, in _close_impl
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2617, in _connection_rollback_impl
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1059, in _rollback_impl
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1057, in _rollback_impl
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 683, in do_rollback
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) Cannot operate on a closed database.
(Background on this error at: https://sqlalche.me/e/14/f405)
``` 

Don't think this has to do with how I'm calling `SearchEngine`. Produces annoying error message when the script finishes.

**Comment by MacHu-GWU** [comment]
Could you show me some codesnippet? I believe you should close it when your query is done since it is a local database
